# Generated by Django 5.0.6 on 2024-07-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_calories', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_proteins', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_fats', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_carbohydrates', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('breakfast', models.ManyToManyField(blank=True, related_name='breakfast_menus', to='recipes.recipe')),
                ('dinner', models.ManyToManyField(blank=True, related_name='dinner_menus', to='recipes.recipe')),
                ('lunch', models.ManyToManyField(blank=True, related_name='lunch_menus', to='recipes.recipe')),
                ('snack', models.ManyToManyField(blank=True, related_name='snack_menus', to='recipes.recipe')),
            ],
        ),
    ]
